name: superhf
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.6.2
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.2.1
  - attrs=22.2.0
  - babel=2.11.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - bleach=5.0.1
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - comm=0.1.2
  - cryptography=39.0.0
  - debugpy=1.6.6
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=1.2.0
  - flit-core=3.8.0
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_resources=5.10.2
  - ipykernel=6.20.2
  - ipython=8.8.0
  - ipython_genutils=0.2.0
  - jedi=0.18.2
  - jinja2=3.1.2
  - json5=0.9.5
  - jsonschema=4.17.3
  - jupyter_client=7.4.9
  - jupyter_core=5.1.3
  - jupyter_events=0.6.3
  - jupyter_server=2.1.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=3.5.3
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.19.0
  - libcxx=14.0.6
  - libffi=3.4.2
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libzlib=1.2.13
  - markupsafe=2.1.2
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - nbclassic=0.4.8
  - nbclient=0.7.2
  - nbconvert=7.2.8
  - nbconvert-core=7.2.8
  - nbconvert-pandoc=7.2.8
  - nbformat=5.7.3
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - openssl=3.0.7
  - packaging=23.0
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.6.2
  - prometheus_client=0.15.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.14.0
  - pyopenssl=23.0.0
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - python=3.11.0
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.4
  - python_abi=3.11=3_cp311
  - pytz=2022.7.1
  - pyyaml=6.0
  - pyzmq=25.0.0
  - readline=8.1.2
  - requests=2.28.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - send2trash=1.8.0
  - setuptools=66.1.1
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - stack_data=0.6.2
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.2
  - traitlets=5.8.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.14
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.4.2
  - wheel=0.38.4
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.11.0
prefix: /opt/anaconda3/envs/superhf
